#!/bin/bash

# Auto-Build Environment Setup
# Configuration Validator Task
# Generated by Planner Agent

set -e

echo "========================================"
echo "Olimpus Configuration Validator"
echo "Development Environment Setup"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# ============================================
# INSTALL DEPENDENCIES
# ============================================
echo ""
echo "[1/3] Installing dependencies..."
if bun install; then
    echo -e "${GREEN}✓ Dependencies installed${NC}"
else
    echo -e "${RED}✗ Failed to install dependencies${NC}"
    exit 1
fi

# ============================================
# BUILD PROJECT
# ============================================
echo ""
echo "[2/3] Building project..."
if bun run build; then
    echo -e "${GREEN}✓ Project built successfully${NC}"
else
    echo -e "${RED}✗ Build failed${NC}"
    exit 1
fi

# ============================================
# TYPE CHECK
# ============================================
echo ""
echo "[3/3] Running type check..."
if bun run typecheck; then
    echo -e "${GREEN}✓ Type check passed${NC}"
else
    echo -e "${YELLOW}⚠ Type check warnings (non-blocking)${NC}"
fi

# ============================================
# SUMMARY
# ============================================
echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Available Commands:"
echo "  bun test              Run all tests"
echo "  bun test --watch     Run tests in watch mode"
echo "  bun run typecheck    TypeScript type checking"
echo "  bun run build        Build the project"
echo "  bun run bin/olimpus.ts validate <config>  Validate config file"
echo ""
echo "Quick Start:"
echo "  bun run bin/olimpus.ts validate olimpus.jsonc"
echo ""
